$(function(){
    $("#icon").click(function(){
        $(".header_menu").slideToggle();
        $(this).toggleClass("active")
    });
});
$(window).resize(function(){
    if(window.innerWidth>=768){
        $("#icon").removeClass("active")
        $(".header_menu").hide();
    }
});

$(function(){
    $("#kero").click(function(){
        $(".info_in").slideToggle();
        $(this).toggleClass("active")
    });
});